CREATE TABLE IF NOT EXISTS `config` (
  `key` VARCHAR(30) NOT NULL,
  `code` VARCHAR(30) NOT NULL,
  `description` VARCHAR(30) NOT NULL,
  `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`key`)
);
